markdown: rdiscount
permalink: /:title/
url: http://wangdaodao.com
name: 王叨叨
author: wangdaodao
qq: 249886288
email: hi@wangdaodao.com
duoshuo: wangdaodao
github: wangdaodao
pygments: true
safe: true
paginate: 10