markdown: rdiscount
permalink: /:title/
url: http://wangdaodao.github.io
name: 王叨叨
author: wangdaodao
qq: 249886288
email: hi@wangdaodao.com
duoshuo: wangdaodao
github: wangdaodao
pygments: true
safe: true
paginate: 20
about: "欢迎观赏、建议、拍砖……"
